### ISSUE TITLE
爬虫警告：UserWarning: Curlm alread closed! quitting from process_data   warnings.warn("Curlm alread closed! quitting from process_data")

### ISSUE THREAD

**Issue by bijiakunkun** [tieyongjie/scrapy-fingerprint#4]
我将scrapy_fingerprint配置到我的scrapy项目中，运行后日志中一直报错：curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (56)，即接收网络请求失败，随机警告UserWarning: Curlm alread closed! quitting from process_data   warnings.warn("Curlm alread closed! quitting from process_data")，可以通过修改scrapy_fingerprint的文件使爬虫变正常吗？
希望能得到解答，Peace And Love！

**Comment by tieyongjie** [comment]
看下这个https://github.com/yifeikong/curl_cffi/issues/234

**Comment by bijiakunkun** [comment]
好的，感谢！！
